export default function Head() {
  return (
    <>
      <title>Post-it</title>
      <meta name="keywords" content="postit, comment to other" />
      <meta name="description" content="Social media fake to learn nextjs13" />
      <meta name="author" content="Adi Nugraha putra" />

      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
